

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    password: '1'
    username: sa
    url: jdbc:h2:tcp://localhost/~/reborn
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  thymeleaf:
    cache: 'false'

  h2:
    console:
      path: /h2-console
      enabled: 'true'

  devtools:
    livereload:
      enabled: 'true'

  jwt:
    secret-key: 'adssdadasdaeijqriqejriejqirjeiwjrwqieiqjeiqwejiqwjeiqjweijqweijqwiejqwiejiq'

  profiles:
    include: oauth

logging:
  level:
    org:
      springframework:
        security:
          web: trace

app:
  auth:
    tokenExpireDate: 1800000
    refresh-token-expire-date: 604800000

file:
  upload:
    directory: 'D:\upload\'
