

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.h2.Driver
    password: '1'
    username: sa
    url: jdbc:h2:tcp://localhost/~/reborn

#  datasource:
#    url: jdbc:mysql://testdb.cmltf5ipyjrf.ap-northeast-2.rds.amazonaws.com:3306/mytestdb
#    username: admin
#    password: gksdntjr
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    driverClassName: org.mariadb.jdbc.Driver
#    password: '1234'
#    username: bootuser
#    url: jdbc:mariadb://localhost:3306/bootex

  thymeleaf:
    cache: 'false'

  h2:
    console:
      path: /h2-console
      enabled: 'true'

  devtools:
    livereload:
      enabled: 'true'

  jwt:
    secret-key: 'adssdadasdaeijqriqejriejqirjeiwjrwqieiqjeiqwejiqwjeiqjweijqweijqwiejqwiejiq'

  profiles:
    include: oauth

logging:
  level:
    org:
      springframework:
        security:
          web: trace

app:
  auth:
    tokenExpireDate: 1800000
    refresh-token-expire-date: 604800000
